### ISSUE TITLE
Set ingress to use cert manager for cluster certificates

### ISSUE THREAD

**Issue by clshaw01** [sixfeetup/cookiecutter-sixiedjango#70]
1.Add a Makefile target to install `certmanager` in the cluster, eg.:
```
certmanager:
  kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml
``` 
2. Add two `ClusterIssuer` resources for the staging and production Let's Encrypt issuers:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-prod
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: {{cookiecutter.email}}
   privateKeySecretRef:
     name: letsencrypt-prod
   solvers:
   - http01:
       ingress:
         class: traefik
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-staging
spec:
 acme:
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   email: {{cookiecutter.email}}
   privateKeySecretRef:
     name: letsencrypt-staging
   solvers:
   - http01:
       ingress:
         class: traefik
```
3. Update the ingress manifest to use the above issuers, eg.:
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: best-frontend
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: {{cookiecutter.domain_name}}
      priority: 10
      services:
        - name: frontend
          port: 3000
  tls:
    certResolver: letsencrypt
```
